(cl:defpackage happy_robo-srv
  (:use )
  (:export
   "TRIGGERWITHCOMMAND"
   "<TRIGGERWITHCOMMAND-REQUEST>"
   "TRIGGERWITHCOMMAND-REQUEST"
   "<TRIGGERWITHCOMMAND-RESPONSE>"
   "TRIGGERWITHCOMMAND-RESPONSE"
  ))

