<?xml version="1.0"?>
<robot name="real" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="PI" value="3.1415926535897931" />

  <xacro:property name="hori_ang" value="${PI*60/180}" />
  <xacro:property name="vert_ang" value="${PI*32.5/180}" />

  <xacro:property name="robot_length" value="5.8" />
  <xacro:property name="robot_width" value="2.5" />
  <xacro:property name="robot_height" value="1.953" />

  <xacro:property name="wheelbase" value="5.65" />
  <xacro:property name="trackwidth" value="2.35" />

  <xacro:property name="LiDAR_height" value="0.325" />
  <xacro:property name="LiDAR_offset" value="0.03" />

  <xacro:property name="imu_length" value="1.89" />
  <xacro:property name="imu_width" value="0.0" />
  <xacro:property name="imu_height" value="1.96" />

  <xacro:property name="wheel_vertical_offset" value="0.0345" />

  <xacro:property name="wheel_radius" value="0.102" />
  <xacro:property name="wheel_width" value="0.040" />

  <xacro:property name="dummy_inertia" value="1e-09"/>

  <xacro:property name="mount_spacing" value="0.120" />

  <material name="dark_grey"><color rgba="0.2 0.2 0.2 1.0" /></material>
  <material name="light_grey"><color rgba="0.4 0.4 0.4 1.0" /></material>
  <material name="yellow"><color rgba="0.8 0.8 0.0 1.0" /></material>
  <material name="black"><color rgba="0.15 0.15 0.15 1.0" /></material>

  <xacro:macro name="wheel" params="prefix *joint_pose">

    <link name="${prefix}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <!-- <material name="black" /> -->
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.477"/>
        <inertia
          ixx="0.0013" ixy="0" ixz="0"
          iyy="0.0024" iyz="0"
          izz="0.0013"/>
      </inertial>
    </link>

    <joint name="${prefix}_wheel" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel_link" />
      <xacro:insert_block name="joint_pose" />
      <axis xyz="0 1 0" />
    </joint>

  <xacro:wheel prefix="front_left">
    <origin xyz="${wheelbase/2} ${trackwidth/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel prefix="front_right">
    <origin xyz="${wheelbase/2} ${-trackwidth/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel prefix="rear_left">
    <origin xyz="${-wheelbase/2} ${trackwidth/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel prefix="rear_right">
    <origin xyz="${-wheelbase/2} ${-trackwidth/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>

    <transmission name="${prefix}_wheel_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}_wheel">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="${prefix}_actuator">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>

  <link name="base_footprint"/>


  <link name="base_link"></link>
  <joint name="base_footprint_to_base_link" type="fixed">
  <parent link="base_footprint"/>
  <child link="base_link"/>
  <origin xyz="0 0 1.953" rpy="0 0 0"/>
</joint>

  <!-- <link name="map"></link> -->
  <!-- <link name="odom"></link> -->

  <!-- <joint name="base_link_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="chassis_link" />
  </joint> -->

  <!-- TODO: Make this internal_imu_link or something, and use a mixed-in xacro
       to supply the joint between it and imu_link. This is important so that imu_link
       always points to the "active" IMU. When an upgrade IMU is connected, the
       internal_imu_link should remain, but imu_link should point to the upgrade one. -->
  <link name="imu_link">
    <inertial>
      <mass value="0.001"/>
      <inertia ixx="${dummy_inertia}" ixy="0.0" ixz="0.0" iyy="${dummy_inertia}" iyz="0.0" izz="${dummy_inertia}"/>
    </inertial>
  </link>
  <joint name="imu_joint" type="fixed">
    <parent link="base_link" />
    <child link="imu_link" />
    <!-- <origin xyz="${imu_length} ${imu_width} ${imu_height}" rpy="0 0 0"/> -->
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>


  <link name="laser_frame_0">
  </link>
  <joint name="laser_joint_0" type="fixed">
    <parent link="base_link" />
    <child link="laser_frame_0" />
    <origin xyz="${robot_length/2 + LiDAR_offset} ${trackwidth/2} ${LiDAR_height - imu_height}" rpy="0 0 0"/>
  </joint>

  <link name="laser_frame_1">
  </link>
  <joint name="laser_joint_1" type="fixed">
    <parent link="base_link" />
    <child link="laser_frame_1" />
    <origin xyz="${robot_length/2 + LiDAR_offset} ${-trackwidth/2} ${LiDAR_height - imu_height}" rpy="0 0 0"/>
  </joint>

  <link name="laser_frame_2">
  </link>
  <joint name="laser_joint_2" type="fixed">
    <parent link="base_link" />
    <child link="laser_frame_2" />
    <origin xyz="${-robot_length/2 + LiDAR_offset} ${-trackwidth/2} ${LiDAR_height - imu_height}" rpy="0 0 ${PI}"/>
  </joint>

  <link name="laser_frame_3">
  </link>
  <joint name="laser_joint_3" type="fixed">
    <parent link="base_link" />
    <child link="laser_frame_3" />
    <origin xyz="${-robot_length/2 + LiDAR_offset} ${trackwidth/2} ${LiDAR_height - imu_height}" rpy="0 0 ${PI}"/>
  </joint>

  <link name="laser_frame_4">
  </link>
  <joint name="laser_joint_4" type="fixed">
    <parent link="base_link" />
    <child link="laser_frame_4" />
    <origin xyz="${wheelbase/2 + imu_length} ${robot_width/2 + LiDAR_offset} ${LiDAR_height - imu_height}" rpy="0 0 ${PI/2}"/>
  </joint>

  <link name="laser_frame_5">
  </link>
  <joint name="laser_joint_5" type="fixed">
    <parent link="base_link" />
    <child link="laser_frame_5" />
    <origin xyz="${wheelbase/2 + imu_length} ${-robot_width/2 + LiDAR_offset} ${LiDAR_height - imu_height}" rpy="0 0 -${PI/2}"/>
  </joint>

  <link name="laser_frame_6">
  </link>
  <joint name="laser_joint_6" type="fixed">
    <parent link="base_link" />
    <child link="laser_frame_6" />
    <origin xyz="${-wheelbase/2 + robot_length/2 - imu_length} ${-robot_width/2 + LiDAR_offset} ${LiDAR_height - imu_height}" rpy="0 0 ${PI/2}"/>
  </joint>

  <link name="laser_frame_7">
  </link>
  <joint name="laser_joint_7" type="fixed">
    <parent link="base_link" />
    <child link="laser_frame_7" />
    <origin xyz="${-wheelbase/2 + robot_length/2 - imu_length} ${robot_width/2 + LiDAR_offset} ${LiDAR_height - imu_height}" rpy="0 0 -${PI/2}"/>
  </joint>

</robot>