// Generated by gencpp from file cyglidar_d2_ros1/SetRunModeRequest.msg
// DO NOT EDIT!


#ifndef CYGLIDAR_D2_ROS1_MESSAGE_SETRUNMODEREQUEST_H
#define CYGLIDAR_D2_ROS1_MESSAGE_SETRUNMODEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cyglidar_d2_ros1
{
template <class ContainerAllocator>
struct SetRunModeRequest_
{
  typedef SetRunModeRequest_<ContainerAllocator> Type;

  SetRunModeRequest_()
    : mode(0)  {
    }
  SetRunModeRequest_(const ContainerAllocator& _alloc)
    : mode(0)  {
  (void)_alloc;
    }



   typedef int32_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::cyglidar_d2_ros1::SetRunModeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cyglidar_d2_ros1::SetRunModeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetRunModeRequest_

typedef ::cyglidar_d2_ros1::SetRunModeRequest_<std::allocator<void> > SetRunModeRequest;

typedef boost::shared_ptr< ::cyglidar_d2_ros1::SetRunModeRequest > SetRunModeRequestPtr;
typedef boost::shared_ptr< ::cyglidar_d2_ros1::SetRunModeRequest const> SetRunModeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cyglidar_d2_ros1::SetRunModeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cyglidar_d2_ros1::SetRunModeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cyglidar_d2_ros1::SetRunModeRequest_<ContainerAllocator1> & lhs, const ::cyglidar_d2_ros1::SetRunModeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cyglidar_d2_ros1::SetRunModeRequest_<ContainerAllocator1> & lhs, const ::cyglidar_d2_ros1::SetRunModeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cyglidar_d2_ros1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cyglidar_d2_ros1::SetRunModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cyglidar_d2_ros1::SetRunModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cyglidar_d2_ros1::SetRunModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cyglidar_d2_ros1::SetRunModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cyglidar_d2_ros1::SetRunModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cyglidar_d2_ros1::SetRunModeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cyglidar_d2_ros1::SetRunModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff63f6ea3c3e9b7504b2cb3ee0a09d92";
  }

  static const char* value(const ::cyglidar_d2_ros1::SetRunModeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff63f6ea3c3e9b75ULL;
  static const uint64_t static_value2 = 0x04b2cb3ee0a09d92ULL;
};

template<class ContainerAllocator>
struct DataType< ::cyglidar_d2_ros1::SetRunModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cyglidar_d2_ros1/SetRunModeRequest";
  }

  static const char* value(const ::cyglidar_d2_ros1::SetRunModeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cyglidar_d2_ros1::SetRunModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 mode   # 0: 2D, 1: 3D, 2: 2D&3D Dual\n"
;
  }

  static const char* value(const ::cyglidar_d2_ros1::SetRunModeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cyglidar_d2_ros1::SetRunModeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetRunModeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cyglidar_d2_ros1::SetRunModeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cyglidar_d2_ros1::SetRunModeRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CYGLIDAR_D2_ROS1_MESSAGE_SETRUNMODEREQUEST_H
