// Generated by gencpp from file cyglidar_d2_ros1/SetRunModeResponse.msg
// DO NOT EDIT!


#ifndef CYGLIDAR_D2_ROS1_MESSAGE_SETRUNMODERESPONSE_H
#define CYGLIDAR_D2_ROS1_MESSAGE_SETRUNMODERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cyglidar_d2_ros1
{
template <class ContainerAllocator>
struct SetRunModeResponse_
{
  typedef SetRunModeResponse_<ContainerAllocator> Type;

  SetRunModeResponse_()
    : success(false)
    , message()  {
    }
  SetRunModeResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::cyglidar_d2_ros1::SetRunModeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cyglidar_d2_ros1::SetRunModeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetRunModeResponse_

typedef ::cyglidar_d2_ros1::SetRunModeResponse_<std::allocator<void> > SetRunModeResponse;

typedef boost::shared_ptr< ::cyglidar_d2_ros1::SetRunModeResponse > SetRunModeResponsePtr;
typedef boost::shared_ptr< ::cyglidar_d2_ros1::SetRunModeResponse const> SetRunModeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cyglidar_d2_ros1::SetRunModeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cyglidar_d2_ros1::SetRunModeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cyglidar_d2_ros1::SetRunModeResponse_<ContainerAllocator1> & lhs, const ::cyglidar_d2_ros1::SetRunModeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cyglidar_d2_ros1::SetRunModeResponse_<ContainerAllocator1> & lhs, const ::cyglidar_d2_ros1::SetRunModeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cyglidar_d2_ros1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cyglidar_d2_ros1::SetRunModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cyglidar_d2_ros1::SetRunModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cyglidar_d2_ros1::SetRunModeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cyglidar_d2_ros1::SetRunModeResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cyglidar_d2_ros1::SetRunModeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cyglidar_d2_ros1::SetRunModeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cyglidar_d2_ros1::SetRunModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::cyglidar_d2_ros1::SetRunModeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::cyglidar_d2_ros1::SetRunModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cyglidar_d2_ros1/SetRunModeResponse";
  }

  static const char* value(const ::cyglidar_d2_ros1::SetRunModeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cyglidar_d2_ros1::SetRunModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
;
  }

  static const char* value(const ::cyglidar_d2_ros1::SetRunModeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cyglidar_d2_ros1::SetRunModeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetRunModeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cyglidar_d2_ros1::SetRunModeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cyglidar_d2_ros1::SetRunModeResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CYGLIDAR_D2_ROS1_MESSAGE_SETRUNMODERESPONSE_H
