// Generated by gencpp from file cyglidar_d2_ros1/SetRunMode.msg
// DO NOT EDIT!


#ifndef CYGLIDAR_D2_ROS1_MESSAGE_SETRUNMODE_H
#define CYGLIDAR_D2_ROS1_MESSAGE_SETRUNMODE_H

#include <ros/service_traits.h>


#include <cyglidar_d2_ros1/SetRunModeRequest.h>
#include <cyglidar_d2_ros1/SetRunModeResponse.h>


namespace cyglidar_d2_ros1
{

struct SetRunMode
{

typedef SetRunModeRequest Request;
typedef SetRunModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetRunMode
} // namespace cyglidar_d2_ros1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cyglidar_d2_ros1::SetRunMode > {
  static const char* value()
  {
    return "7fe3d509a33a499434e32bc293dc9f6b";
  }

  static const char* value(const ::cyglidar_d2_ros1::SetRunMode&) { return value(); }
};

template<>
struct DataType< ::cyglidar_d2_ros1::SetRunMode > {
  static const char* value()
  {
    return "cyglidar_d2_ros1/SetRunMode";
  }

  static const char* value(const ::cyglidar_d2_ros1::SetRunMode&) { return value(); }
};


// service_traits::MD5Sum< ::cyglidar_d2_ros1::SetRunModeRequest> should match
// service_traits::MD5Sum< ::cyglidar_d2_ros1::SetRunMode >
template<>
struct MD5Sum< ::cyglidar_d2_ros1::SetRunModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cyglidar_d2_ros1::SetRunMode >::value();
  }
  static const char* value(const ::cyglidar_d2_ros1::SetRunModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cyglidar_d2_ros1::SetRunModeRequest> should match
// service_traits::DataType< ::cyglidar_d2_ros1::SetRunMode >
template<>
struct DataType< ::cyglidar_d2_ros1::SetRunModeRequest>
{
  static const char* value()
  {
    return DataType< ::cyglidar_d2_ros1::SetRunMode >::value();
  }
  static const char* value(const ::cyglidar_d2_ros1::SetRunModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cyglidar_d2_ros1::SetRunModeResponse> should match
// service_traits::MD5Sum< ::cyglidar_d2_ros1::SetRunMode >
template<>
struct MD5Sum< ::cyglidar_d2_ros1::SetRunModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cyglidar_d2_ros1::SetRunMode >::value();
  }
  static const char* value(const ::cyglidar_d2_ros1::SetRunModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cyglidar_d2_ros1::SetRunModeResponse> should match
// service_traits::DataType< ::cyglidar_d2_ros1::SetRunMode >
template<>
struct DataType< ::cyglidar_d2_ros1::SetRunModeResponse>
{
  static const char* value()
  {
    return DataType< ::cyglidar_d2_ros1::SetRunMode >::value();
  }
  static const char* value(const ::cyglidar_d2_ros1::SetRunModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CYGLIDAR_D2_ROS1_MESSAGE_SETRUNMODE_H
