// Generated by gencpp from file happy_robo/AlignAndGoalPoseStamped.msg
// DO NOT EDIT!


#ifndef HAPPY_ROBO_MESSAGE_ALIGNANDGOALPOSESTAMPED_H
#define HAPPY_ROBO_MESSAGE_ALIGNANDGOALPOSESTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/PoseStamped.h>

namespace happy_robo
{
template <class ContainerAllocator>
struct AlignAndGoalPoseStamped_
{
  typedef AlignAndGoalPoseStamped_<ContainerAllocator> Type;

  AlignAndGoalPoseStamped_()
    : header()
    , align_pose()
    , goal_pose()  {
    }
  AlignAndGoalPoseStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , align_pose(_alloc)
    , goal_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _align_pose_type;
  _align_pose_type align_pose;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _goal_pose_type;
  _goal_pose_type goal_pose;





  typedef boost::shared_ptr< ::happy_robo::AlignAndGoalPoseStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::happy_robo::AlignAndGoalPoseStamped_<ContainerAllocator> const> ConstPtr;

}; // struct AlignAndGoalPoseStamped_

typedef ::happy_robo::AlignAndGoalPoseStamped_<std::allocator<void> > AlignAndGoalPoseStamped;

typedef boost::shared_ptr< ::happy_robo::AlignAndGoalPoseStamped > AlignAndGoalPoseStampedPtr;
typedef boost::shared_ptr< ::happy_robo::AlignAndGoalPoseStamped const> AlignAndGoalPoseStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::happy_robo::AlignAndGoalPoseStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::happy_robo::AlignAndGoalPoseStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::happy_robo::AlignAndGoalPoseStamped_<ContainerAllocator1> & lhs, const ::happy_robo::AlignAndGoalPoseStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.align_pose == rhs.align_pose &&
    lhs.goal_pose == rhs.goal_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::happy_robo::AlignAndGoalPoseStamped_<ContainerAllocator1> & lhs, const ::happy_robo::AlignAndGoalPoseStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace happy_robo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::happy_robo::AlignAndGoalPoseStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::happy_robo::AlignAndGoalPoseStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::happy_robo::AlignAndGoalPoseStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::happy_robo::AlignAndGoalPoseStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::happy_robo::AlignAndGoalPoseStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::happy_robo::AlignAndGoalPoseStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::happy_robo::AlignAndGoalPoseStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bed5bcb1a5fb9623874074ff155a0f6d";
  }

  static const char* value(const ::happy_robo::AlignAndGoalPoseStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbed5bcb1a5fb9623ULL;
  static const uint64_t static_value2 = 0x874074ff155a0f6dULL;
};

template<class ContainerAllocator>
struct DataType< ::happy_robo::AlignAndGoalPoseStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "happy_robo/AlignAndGoalPoseStamped";
  }

  static const char* value(const ::happy_robo::AlignAndGoalPoseStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::happy_robo::AlignAndGoalPoseStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"geometry_msgs/PoseStamped align_pose\n"
"geometry_msgs/PoseStamped goal_pose\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::happy_robo::AlignAndGoalPoseStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::happy_robo::AlignAndGoalPoseStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.align_pose);
      stream.next(m.goal_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AlignAndGoalPoseStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::happy_robo::AlignAndGoalPoseStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::happy_robo::AlignAndGoalPoseStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "align_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.align_pose);
    s << indent << "goal_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAPPY_ROBO_MESSAGE_ALIGNANDGOALPOSESTAMPED_H
