// Generated by gencpp from file happy_robo/TriggerWithCommandRequest.msg
// DO NOT EDIT!


#ifndef HAPPY_ROBO_MESSAGE_TRIGGERWITHCOMMANDREQUEST_H
#define HAPPY_ROBO_MESSAGE_TRIGGERWITHCOMMANDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace happy_robo
{
template <class ContainerAllocator>
struct TriggerWithCommandRequest_
{
  typedef TriggerWithCommandRequest_<ContainerAllocator> Type;

  TriggerWithCommandRequest_()
    : command(0)
    , degree(0.0)  {
    }
  TriggerWithCommandRequest_(const ContainerAllocator& _alloc)
    : command(0)
    , degree(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _command_type;
  _command_type command;

   typedef double _degree_type;
  _degree_type degree;





  typedef boost::shared_ptr< ::happy_robo::TriggerWithCommandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::happy_robo::TriggerWithCommandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TriggerWithCommandRequest_

typedef ::happy_robo::TriggerWithCommandRequest_<std::allocator<void> > TriggerWithCommandRequest;

typedef boost::shared_ptr< ::happy_robo::TriggerWithCommandRequest > TriggerWithCommandRequestPtr;
typedef boost::shared_ptr< ::happy_robo::TriggerWithCommandRequest const> TriggerWithCommandRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::happy_robo::TriggerWithCommandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::happy_robo::TriggerWithCommandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::happy_robo::TriggerWithCommandRequest_<ContainerAllocator1> & lhs, const ::happy_robo::TriggerWithCommandRequest_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command &&
    lhs.degree == rhs.degree;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::happy_robo::TriggerWithCommandRequest_<ContainerAllocator1> & lhs, const ::happy_robo::TriggerWithCommandRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace happy_robo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::happy_robo::TriggerWithCommandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::happy_robo::TriggerWithCommandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::happy_robo::TriggerWithCommandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::happy_robo::TriggerWithCommandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::happy_robo::TriggerWithCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::happy_robo::TriggerWithCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::happy_robo::TriggerWithCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f1ac98a30aab4f95cec18c5691cae85";
  }

  static const char* value(const ::happy_robo::TriggerWithCommandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f1ac98a30aab4f9ULL;
  static const uint64_t static_value2 = 0x5cec18c5691cae85ULL;
};

template<class ContainerAllocator>
struct DataType< ::happy_robo::TriggerWithCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "happy_robo/TriggerWithCommandRequest";
  }

  static const char* value(const ::happy_robo::TriggerWithCommandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::happy_robo::TriggerWithCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 command\n"
"float64 degree  # 새로 추가\n"
;
  }

  static const char* value(const ::happy_robo::TriggerWithCommandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::happy_robo::TriggerWithCommandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.degree);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TriggerWithCommandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::happy_robo::TriggerWithCommandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::happy_robo::TriggerWithCommandRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<int32_t>::stream(s, indent + "  ", v.command);
    s << indent << "degree: ";
    Printer<double>::stream(s, indent + "  ", v.degree);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAPPY_ROBO_MESSAGE_TRIGGERWITHCOMMANDREQUEST_H
