// Generated by gencpp from file happy_robo/TriggerWithCommand.msg
// DO NOT EDIT!


#ifndef HAPPY_ROBO_MESSAGE_TRIGGERWITHCOMMAND_H
#define HAPPY_ROBO_MESSAGE_TRIGGERWITHCOMMAND_H

#include <ros/service_traits.h>


#include <happy_robo/TriggerWithCommandRequest.h>
#include <happy_robo/TriggerWithCommandResponse.h>


namespace happy_robo
{

struct TriggerWithCommand
{

typedef TriggerWithCommandRequest Request;
typedef TriggerWithCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TriggerWithCommand
} // namespace happy_robo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::happy_robo::TriggerWithCommand > {
  static const char* value()
  {
    return "47151e7a2db9a3278116246d030bbe6b";
  }

  static const char* value(const ::happy_robo::TriggerWithCommand&) { return value(); }
};

template<>
struct DataType< ::happy_robo::TriggerWithCommand > {
  static const char* value()
  {
    return "happy_robo/TriggerWithCommand";
  }

  static const char* value(const ::happy_robo::TriggerWithCommand&) { return value(); }
};


// service_traits::MD5Sum< ::happy_robo::TriggerWithCommandRequest> should match
// service_traits::MD5Sum< ::happy_robo::TriggerWithCommand >
template<>
struct MD5Sum< ::happy_robo::TriggerWithCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::happy_robo::TriggerWithCommand >::value();
  }
  static const char* value(const ::happy_robo::TriggerWithCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::happy_robo::TriggerWithCommandRequest> should match
// service_traits::DataType< ::happy_robo::TriggerWithCommand >
template<>
struct DataType< ::happy_robo::TriggerWithCommandRequest>
{
  static const char* value()
  {
    return DataType< ::happy_robo::TriggerWithCommand >::value();
  }
  static const char* value(const ::happy_robo::TriggerWithCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::happy_robo::TriggerWithCommandResponse> should match
// service_traits::MD5Sum< ::happy_robo::TriggerWithCommand >
template<>
struct MD5Sum< ::happy_robo::TriggerWithCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::happy_robo::TriggerWithCommand >::value();
  }
  static const char* value(const ::happy_robo::TriggerWithCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::happy_robo::TriggerWithCommandResponse> should match
// service_traits::DataType< ::happy_robo::TriggerWithCommand >
template<>
struct DataType< ::happy_robo::TriggerWithCommandResponse>
{
  static const char* value()
  {
    return DataType< ::happy_robo::TriggerWithCommand >::value();
  }
  static const char* value(const ::happy_robo::TriggerWithCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HAPPY_ROBO_MESSAGE_TRIGGERWITHCOMMAND_H
