// Generated by gencpp from file happy_robo/TriggerWithCommandResponse.msg
// DO NOT EDIT!


#ifndef HAPPY_ROBO_MESSAGE_TRIGGERWITHCOMMANDRESPONSE_H
#define HAPPY_ROBO_MESSAGE_TRIGGERWITHCOMMANDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace happy_robo
{
template <class ContainerAllocator>
struct TriggerWithCommandResponse_
{
  typedef TriggerWithCommandResponse_<ContainerAllocator> Type;

  TriggerWithCommandResponse_()
    : success(false)
    , message()  {
    }
  TriggerWithCommandResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::happy_robo::TriggerWithCommandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::happy_robo::TriggerWithCommandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TriggerWithCommandResponse_

typedef ::happy_robo::TriggerWithCommandResponse_<std::allocator<void> > TriggerWithCommandResponse;

typedef boost::shared_ptr< ::happy_robo::TriggerWithCommandResponse > TriggerWithCommandResponsePtr;
typedef boost::shared_ptr< ::happy_robo::TriggerWithCommandResponse const> TriggerWithCommandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::happy_robo::TriggerWithCommandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::happy_robo::TriggerWithCommandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::happy_robo::TriggerWithCommandResponse_<ContainerAllocator1> & lhs, const ::happy_robo::TriggerWithCommandResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::happy_robo::TriggerWithCommandResponse_<ContainerAllocator1> & lhs, const ::happy_robo::TriggerWithCommandResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace happy_robo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::happy_robo::TriggerWithCommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::happy_robo::TriggerWithCommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::happy_robo::TriggerWithCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::happy_robo::TriggerWithCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::happy_robo::TriggerWithCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::happy_robo::TriggerWithCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::happy_robo::TriggerWithCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::happy_robo::TriggerWithCommandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::happy_robo::TriggerWithCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "happy_robo/TriggerWithCommandResponse";
  }

  static const char* value(const ::happy_robo::TriggerWithCommandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::happy_robo::TriggerWithCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
;
  }

  static const char* value(const ::happy_robo::TriggerWithCommandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::happy_robo::TriggerWithCommandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TriggerWithCommandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::happy_robo::TriggerWithCommandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::happy_robo::TriggerWithCommandResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAPPY_ROBO_MESSAGE_TRIGGERWITHCOMMANDRESPONSE_H
